[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deep-fake-detection"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
  "Flask>=2.2.5",
  "numpy",
  "pandas",
  # other runtime deps here
]
